name: design_system_example
description: Catálogo interactivo de componentes del Design System IAutomat
publish_to: none
version: 1.0.0+1

environment:
  sdk: '>=3.8.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  iautomat_design_system:
    path: ../
  go_router: ^14.6.2
  provider: ^6.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true