name: iautomat_design_system
description: "Sistema de diseño empresarial completo para Flutter - 70+ componentes con prefijo DS, Material 3, accesibilidad WCAG 2.0"
publish_to: none
version: 1.0.0


environment:
  sdk: '>=3.8.0 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.2.1
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
  fl_chart: ^0.69.2
  vector_math: ^2.1.4
  intl: ^0.19.0
  share_plus: ^10.1.4
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.13
  freezed: ^2.5.7
  json_serializable: ^6.8.0


  
