name: Deploy to Firebase Hosting

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.35.3'
        channel: 'stable'
        cache: true

    - name: Verify Flutter and Dart versions
      run: |
        flutter --version
        dart --version

    - name: Install main package dependencies
      run: flutter pub get

    - name: Install example dependencies
      run: |
        cd example
        flutter pub get

    - name: Run tests
      run: |
        cd example
        flutter test
      continue-on-error: true  # No bloquear si no hay tests

    - name: Build for web
      run: |
        cd example
        flutter build web --release --base-href /

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Install Firebase CLI
      run: npm install -g firebase-tools

    - name: Deploy to Firebase Hosting (Preview)
      if: github.event_name == 'pull_request'
      run: |
        cd example
        firebase hosting:channel:deploy pr-${{ github.event.number }} --project iautomatdesignsystem --non-interactive
      env:
        FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}

    - name: Deploy to Firebase Hosting (Production)
      if: github.ref == 'refs/heads/main' && github.event_name == 'push'
      run: |
        cd example
        firebase deploy --only hosting --project iautomatdesignsystem --non-interactive
      env:
        FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}